name: GameStoreDeploy

on:
  push:
    branches:
      - dev
    release:
      types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare WordPress Zip
        run: |
          WP_LINK=$(cat wp-version-control.cfg)
          wget -O "./wordpress.zip" $WP_LINK
      - name: Prepare plugins and theme zip
        run: zip -r wpcontent.zip plugins mu-plugins themes
      - name: Copy Zips to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "./wordpress.zip, ./wpcontent.zip"
          target: ${{ github.event_name == 'push' && '/home/huts6/hutsaluck.site/dev' || '/home/huts6/hutsaluck.site/live' }}
      - name: Enable Maintenance Mode
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: ".maintenance"
          target: ${{ github.event_name == 'push' && '/home/huts6/hutsaluck.site/dev' || '/home/huts6/hutsaluck.site/live' }}
      - name: Update WordPress Core
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            find "${{ github.event_name == 'push' && '/home/huts6/hutsaluck.site/dev' || '/home/huts6/hutsaluck.site/live' }}" -type f -name "*.php" ! -name "wp-config.php" -delete
            rm -r "${{ github.event_name == 'push' && '/home/huts6/hutsaluck.site/dev' || '/home/huts6/hutsaluck.site/live' }}/wp-admin/" "${{ github.event_name == 'push' && '/home/huts6/hutsaluck.site/dev' || '/home/huts6/hutsaluck.site/live' }}/wp-includes/"
            unzip -o "${{ github.event_name == 'push' && '/home/huts6/hutsaluck.site/dev' || 'public_html/live.geniuscourses.com' }}/wordpress.zip" -d "${{ github.event_name == 'push' && '/home/huts6/hutsaluck.site/dev' || '/home/huts6/hutsaluck.site/live' }}/"
            mv "${{ github.event_name == 'push' && '/home/huts6/hutsaluck.site/dev' || '/home/huts6/hutsaluck.site/live' }}/wordpress"/* "${{ github.event_name == 'push' && '/home/huts6/hutsaluck.site/dev' || '/home/huts6/hutsaluck.site/live' }}/"
            rm -r "${{ github.event_name == 'push' && '/home/huts6/hutsaluck.site/dev' || '/home/huts6/hutsaluck.site/live' }}/wordpress"
      - name: Update Plugins and Theme
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rm -rf "${{ github.event_name == 'push' && '/home/huts6/hutsaluck.site/dev' || '/home/huts6/hutsaluck.site/live' }}/wp-content/plugins" "${{ github.event_name == 'push' && '/home/huts6/hutsaluck.site/dev' || '/home/huts6/hutsaluck.site/live' }}/wp-content/mu-plugins" "${{ github.event_name == 'push' && '/home/huts6/hutsaluck.site/dev' || '/home/huts6/hutsaluck.site/live' }}/wp-content/themes"
            unzip -o "${{ github.event_name == 'push' && '/home/huts6/hutsaluck.site/dev' || '/home/huts6/hutsaluck.site/live' }}/wpcontent.zip" -d "${{ github.event_name == 'push' && '/home/huts6/hutsaluck.site/dev' || '/home/huts6/hutsaluck.site/live' }}/wp-content/"
      - name: Disable Maintenance Mode and Remove zips
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rm -f "${{ github.event_name == 'push' && '/home/huts6/hutsaluck.site/dev' || '/home/huts6/hutsaluck.site/live' }}/.maintenance"
            rm -f "${{ github.event_name == 'push' && '/home/huts6/hutsaluck.site/dev' || '/home/huts6/hutsaluck.site/live' }}/wpcontent.zip"
            rm -f "${{ github.event_name == 'push' && '/home/huts6/hutsaluck.site/dev' || '/home/huts6/hutsaluck.site/live' }}/wordpress.zip"